---
reloader:
  ignoreJobs: true
  ignoreCronJobs: true
  reloadOnCreate: true
  reloadOnDelete: true

  logLevel: info
  reloadStrategy: env-vars
  ignoreNamespaces: kube-system,cilium,rook-ceph

  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 256Mi
