---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-configuration
data:
  # cluster configuration
  SITE: muc
  CILIUM_CLUSTER_ID: "2"

  # network configuration
  NODE_IP: "10.1.50.1"
  ROUTER_IP: "10.1.0.1"

  # domain names
  HOME_DOMAIN: home.muehlbachler.io
  LOCAL_HOME_DOMAIN: muc.home.muehlbachler.io
  INTERNAL_DOMAIN: internal.muehlbachler.io
  LOCAL_INTERNAL_DOMAIN: muc.internal.muehlbachler.io

  # cluster issuers
  PUBLIC_CLUSTER_ISSUER: cluster-issuer-home-muehlbachler-io
  INTERNAL_CLUSTER_ISSUER: cluster-issuer-internal-muehlbachler-io

  # CIDRs
  CILIUM_IPV4_POD_CIDR: "10.102.0.0/16"
  CILIUM_IPV6_POD_CIDR: "fc00:db8:102::/112"

  # load balancer
  METALLB_LB_CLASS: "io.metallb/load-balancer"
  METALLB_IP_ANNOTATION: "metallb.io/loadBalancerIPs"
  CILIUM_LB_CLASS: "io.cilium/bgp-control-plane"
  CILIUM_L2_LB_CLASS: "io.cilium/l2-announcer"
  CILIUM_IP_ANNOTATION: "lbipam.cilium.io/ips"
  # traefik specific load balancer
  TRAEFIK_LB_CLASS: "io.cilium/l2-announcer"
  TRAEFIK_IP_ANNOTATION: "lbipam.cilium.io/ips"
  # ip addresses for services
  TRAEFIK_IP: "10.1.72.1,fd40:2e3:42a::1000:3:3:1"
  OMADA_CONTROLLER_IP: "10.1.71.1,fd40:2e3:42a::1000:3:2:1"
  OMADA_CONTROLLER_IPV4: "10.1.71.1"
  OMADA_CONTROLLER_IPV6: "fd40:2e3:42a::1000:3:2:1"

  # public ip addresses
  PUBLIC_IP: "88.217.198.211"

  # storage classes
  DEFAULT_STORAGE_CLASS: "rook-ceph-block"
