---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: democratic-csi-driver-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |-
          driver: zfs-generic-iscsi
          sshConnection:
            host: {{ .host }} 
            port: 22
            username: {{ .username }}
            password: {{ .password }}

          zfs:
            datasetParentName: zfs-pool/k8s/vols
            detachedSnapshotsDatasetParentName: zfs-pool/k8s/snaps
            datasetEnableQuotas: true
            zvolEnableReservation: false
            zvolCompression: lz4

          iscsi:
            shareStrategy: targetCli
            shareStrategyTargetCli:
              # sudoEnabled: true
              basename: iqn.1993-08.org.debian
              tpg:
                attributes:
                  authentication: 0
                  generate_node_acls: 1
                  cache_dynamic_acls: 1
                  demo_mode_write_protect: 0
                auth:
                  # CHAP
                  # userid: "foo"
                  # password: "bar"
                  # mutual CHAP
                  # mutual_userid: "baz"
                  # mutual_password: "bar"
              block:
                attributes:
                  emulate_tpu: 0
            targetPortal: {{ .host }} 
            targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
            interface: ""

            # MUST ensure uniqueness
            # full iqn limit is 223 bytes, plan accordingly
            # default is "{{ name }}"
            nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

          _private:
            csi:
              volume:
                # note the volume length must *always* be the same for every call for the same volume by the CO
                # the length must NOT execeed 128 characters
                # must start with an alphanumeric character
                # must only contain alphnumeric characters or `-` or `_`
                idTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  data:
    - secretKey: host
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: democratic-csi-credentials
        property: host
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: democratic-csi-credentials
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: democratic-csi-credentials
        property: password
