---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-configuration
data:
  # cluster configuration
  SITE: hochschule-burgenland

  # cilium
  K8S_SERVICE_PORT: "6443"
  CILIUM_CGROUP_AUTO_MOUNT_ENABLED: "true"
  CILIUM_CGROUP_HOST_ROOT: "/run/cilium/cgroupv2"

  # domain names
  PUBLIC_DOMAIN: hochschule-burgenland.muehlbachler.xyz
  INTERNAL_DOMAIN: internal.muehlbachler.xyz
  LOCAL_INTERNAL_DOMAIN: hochschule-burgenland.internal.muehlbachler.xyz
  LOCAL_HOME_DOMAIN: hochschule-burgenland.muehlbachler.xyz

  # cluster issuers
  PUBLIC_CLUSTER_ISSUER: cluster-issuer-muehlbachler-xyz
  INTERNAL_CLUSTER_ISSUER: cluster-issuer-muehlbachler-xyz

  # CIDRs
  CILIUM_IPV4_POD_CIDR: "10.103.0.0/16"
  CILIUM_IPV6_POD_CIDR: "fc00:db8:103::/112"

  # load balancer
  LB_IP_ANNOTATION: "metallb.io/loadBalancerIPs"
  TRAEFIK_IP: "10.100.72.1,2a01:4f8:121:14e2:100:3:3:1"

  # public ip addresses
  PUBLIC_IP: "178.63.69.250,2a01:4f8:121:14e2:100:3:3:1"

  # storage classes
  DEFAULT_STORAGE_CLASS: "zfs"
