---
apiVersion: v2
name: external-dns-google
description: Customized External DNS for Google

version: 1.0.0

type: application

maintainers:
  - name: Daniel Muehlbachler-Pietrzykowski
    email: daniel@muehlbachler.io

appVersion: "0.0.0"

dependencies:
  - name: external-dns
    version: 6.23.2
    repository: oci://registry-1.docker.io/bitnamicharts
