---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - ./configmap-env.yaml
  - ./external-secret-mealie-config.yaml
  - ./external-secret-mealie-database.yaml
  - ./external-secret-mealie-openai.yaml
  - ./external-secret-mealie-smtp.yaml
  - ./external-secret-cloudnativepg-barman-credentials.yaml
  - ./postgresql.yaml
  - ./postgresql-objectstore-scaleway.yaml
  - ./postgresql-backup.yaml
