---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - ciliumbgpclusterconfig.yaml
  - ciliumpeerconfig.yaml
  - ciliumbgpadvertisement.yaml
  - ciliuml2announcementpolicy.yaml
  - ciliumloadbalancerpool-default.yaml
  - ciliumloadbalancerpool-l2.yaml
