---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - ./configmap-env.yaml
  - ./configmap-init.yaml
  - ./external-secret-samba-config.yaml
  - ./external-secret-immich-config.yaml
  - ./external-secret-immich-database.yaml
  - ./external-secret-cloudnativepg-barman-credentials.yaml
  - ./postgresql.yaml
  - ./postgresql-objectstore-scaleway.yaml
  - ./postgresql-backup.yaml
