---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./templates/repository.yaml
  - ./templates/release.yaml
  - ./templates/extensions.yaml
configMapGenerator:
  - name: traefik-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
