---
proxyVarsAsSecrets: false
config:
  configFile: ""

alphaConfig:
  enabled: true
  existingSecret: frigate-auth-proxy-config

deploymentAnnotations:
  reloader.stakater.com/auto: "false"

extraArgs:
  - --email-domain=*
  - --redirect-url=https://nvr.${LOCAL_HOME_DOMAIN}/oauth2/callback

envFrom:
  - secretRef:
      name: frigate-auth-proxy-env

service:
  ipDualStack:
    enabled: true

ingress:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    memory: 100Mi
