---
loadBalancerClass: io.metallb/load-balancer

rbac:
  create: true
psp:
  create: true
controller:
  resources:
    requests:
      cpu: 10m
      memory: 151Mi
    limits:
      memory: 151Mi
speaker:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
  frr:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  frrMetrics:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  reloader:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
