---
apiVersion: v2
name: traefik
description: Customized Traefik

version: 1.0.0

type: application

maintainers:
  - name: Daniel Muehlbachler-Pietrzykowski
    email: daniel@muehlbachler.io

appVersion: "0.0.0"

dependencies:
  - name: traefik
    version: 23.1.0
    repository: https://helm.traefik.io/traefik
