---
rollOutCiliumPods: true

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - ${CILIUM_IPV4_POD_CIDR}
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv6PodCIDRList:
      - ${CILIUM_IPV6_POD_CIDR}
    clusterPoolIPv6MaskSize: 120
ipv6:
  enabled: true

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"

k8sServiceHost: 127.0.0.1
k8sServicePort: ${K8S_SERVICE_PORT:-7445}

k8sClientRateLimit:
  qps: 30
  burst: 60

bgpControlPlane:
  enabled: true

l2announcements:
  enabled: false
externalIPs:
  enabled: true

defaultLBServiceIPAM: none # FIXME: lb class

cgroup:
  autoMount:
    enabled: ${CILIUM_CGROUP_AUTO_MOUNT_ENABLED:-false}
  hostRoot: ${CILIUM_CGROUP_HOST_ROOT:-/sys/fs/cgroup}

bpf:
  masquerade: true
  lbExternalClusterIP: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

prometheus:
  enabled: true

resources:
  requests:
    cpu: 49m
    memory: 1174Mi
  limits:
    memory: 2048Mi

operator:
  replicas: 1
  rollOutPods: true
  prometheus:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 218Mi
    limits:
      memory: 218Mi

envoy:
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      memory: 192Mi

preflight:
  enabled: false

hubble:
  enabled: false
