---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/
  - ../../../common/infrastructure/kubelet-serving-cert-approver/
  - ../../../common/infrastructure/metrics-server/
  - ../../../common/infrastructure/generic-device-plugin/
  - ./external-secrets/
  - ./rook-ceph/
  - ../../../common/infrastructure/traefik/
  # - ./flux-extensions/
  - ../../../common/infrastructure/reloader/
