{{- range $name, $app := .Values.applications -}}
{{- $valuesFiles := printf "%s" (default $app.path $app.valuesPath) -}}
{{- $appName := printf "%s%s-%s" (ternary (printf "%s-" $.Values.global.prefix) "" (ne $.Values.global.prefix "")) $name $.Values.global.environment -}}
{{- $sourceRepoUrl :=  (default $.Values.global.spec.source.repoURL $app.sourceRepoURL) -}}
{{- $valuesRepoUrl := (default $.Values.global.spec.values.repoURL $app.valuesRepoURL) -}}
{{- if not $app.disabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ default $.Values.global.spec.syncWave $app.syncWave }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ tpl $app.project $ }}
  sources:
    - repoURL: {{ $sourceRepoUrl }}
      targetRevision: {{ default $.Values.global.spec.source.targetRevision $app.sourceTargetRevision }}
      {{- if not (and $app.sourceRepoURL $app.sourceTargetRevision) }}
      path: {{ $app.path }}
      {{- end }}
      {{- if default (eq $.Values.global.spec.helm.enabled true) (eq $app.helm true) }}
      helm:
        releaseName: {{ tpl (default $appName $app.releaseName) $ }}
        valueFiles:
        {{- range (default $.Values.global.spec.helm.valueFiles .valueFiles) }}
          - {{ if ne $sourceRepoUrl $valuesRepoUrl -}}$values/{{- end -}}{{ $valuesFiles }}/{{ . }}
        {{- end }}
      {{- end }}
    {{- if ne $sourceRepoUrl $valuesRepoUrl }}
    - repoURL: {{ $valuesRepoUrl }}
      targetRevision: {{ default $.Values.global.spec.values.targetRevision $app.valuesTargetRevision }}
      ref: values
    {{- end }}
  destination:
    namespace: {{ tpl (default $.Values.global.spec.namespace $app.namespace) $ }}
    server: https://kubernetes.default.svc
  {{- if and (default $.Values.global.spec.helm.enabled $app.helm) (default $.Values.global.spec.ignoreDifferences $app.ignoreDifferences) }}
  ignoreDifferences:
    {{- (default $.Values.global.spec.ignoreDifferences $app.ignoreDifferences) | toYaml | nindent 4 }}
  {{- end }}
  syncPolicy:
    {{- if (default $.Values.global.spec.enableAutomated $app.enableAutomated) }}
    automated:
      {{- if default $.Values.global.spec.helm.enabled $app.helm }}
      prune: false
      allowEmpty: false
      {{- end }}
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace={{ ternary "true" "false" (ne (default $.Values.global.spec.namespace $app.namespace) "argocd") }}
      - FailOnSharedResource=true
    {{- with (default $.Values.global.spec.syncOptions $app.syncOptions) -}}
      {{ . | toYaml |  nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
