---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./templates/extensions.yaml
  - ./templates/release.yaml
configMapGenerator:
  - name: external-dns-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
