---
fullnameOverride: emqx

envFromSecret: home-assistant-emqx

replicaCount: 1

ingress:
  dashboard:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "${INTERNAL_CLUSTER_ISSUER}"
      external-dns.alpha.kubernetes.io/provider: internal
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - &domain emqx.iot.${LOCAL_INTERNAL_DOMAIN}
    tls:
      - secretName: home-assistant-emqx-tls-cert
        hosts:
          - *domain

persistence:
  enabled: true
  storageClassName: ${DEFAULT_STORAGE_CLASS}
  accessMode: ReadWriteOnce
  size: 512Mi

ssl:
  enabled: true
  useExisting: true
  existingName: emqx-tls

resources:
  requests:
    cpu: 10m
    memory: 384Mi
  limits:
    memory: 384Mi
