{{- range $k, $v := .Values.zones }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-{{ (regexReplaceAllLiteral "\\W+" $k "-") | lower }}
spec:
  acme:
    email: "{{ $.Values.acme.email }}"
    privateKeySecretRef:
      name: cluster-issuer-{{ (regexReplaceAllLiteral "\\W+" $k "-") | lower }}-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector:
          dnsZones:
            - {{ $k }}
        dns01:
          cloudDNS:
            project: {{ $v.project }}
            hostedZoneName: ${{ $v.hostedZoneName }}
            serviceAccountSecretRef:
              key: credentials.json
              name: cert-manager-google
{{- end }}
