---
args:
  - --enable-dependency-version-upgrades

provider:
  packages: []
configuration:
  packages: []
function:
  packages: []

resourcesCrossplane:
  requests:
    cpu: 10m
    memory: 386Mi
  limits:
    memory: 386Mi

resourcesRBACManager:
  requests:
    cpu: 5m
    memory: 64Mi
  limits:
    memory: 64Mi
