---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./templates/repository.yaml
  - ./templates/extensions.yaml
  - ./templates/release.yaml
configMapGenerator:
  - name: samba-jane-doe-backup-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yml
