---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-rag-env
data:
  DB_HOST: librechat-postgresql-rw
  DB_PORT: "5432"
  POSTGRES_DB: librechat-rag
  EMBEDDINGS_PROVIDER: google_genai
  EMBEDDINGS_MODEL: gemini-embedding-001
  COLLECTION_NAME: librechatrag
  RAG_UPLOAD_DIR: /app/uploads/
  PDF_EXTRACT_IMAGES: "true"
