---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APPLICATION_NAMESPACE}
resources:
  - ./configmap-env.yaml
  - ./configmap-rag-env.yaml
  - ./configmap.yaml
  - ./external-secret-librechat-database.yaml
  - ./external-secret-librechat-meilisearch-master-key.yaml
  - ./external-secret-librechat-secrets.yaml
  - ./external-secret-librechat-rag-secrets.yaml
  - ./postgresql.yaml
